name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Extract repo and Angular project names
        shell: bash
        run: |
          # REPO_NAME becomes only the repo part of owner/repo
          echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          # PROJECT_NAME is the first project key in angular.json (matches angular.json structure)
          PROJECT_NAME=$(node -e "console.log(Object.keys(require('./angular.json').projects)[0])")
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
          echo "Detected PROJECT_NAME=$PROJECT_NAME"
          echo "Detected REPO_NAME=${GITHUB_REPOSITORY#*/}"

      - name: Build (production) with correct base-href
        env:
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          REPO_NAME: ${{ env.REPO_NAME }}
        run: |
          # Build production output; base-href ensures assets are resolved for repo-hosted pages
          npm run build -- --configuration production --project "$PROJECT_NAME" --base-href "/$REPO_NAME/"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/${{ env.PROJECT_NAME }}
          publish_branch: gh-pages
